config/routes.rb
Rails.application.routes.draw do 
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  root 'simple_pages#landing_page'
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get '/products', to: 'products#index'
  get '/orders', to: 'orders#index'
  post 'simple_pages/thank_you'
  post 'payments/create'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class= "container-fluid">
        <header>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName navbar-brand">
            <%= link_to "MountainStyle", root_path %>
          </div> <!--end projectName-->
        </header> <!--end navbar-header -->
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
            <li>
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path) %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= form_with(url: products_path, method: 'get', local: true, class: 'nav-search') do |form| %>
                <%= form.text_field :q, id: 'q',placeholder:"Search for..", class: 'nav_searchbar', value: params[:q] %>
                <%= button_tag(type: 'submit', class: "btn btn-primary, nav_search_submit") do %>
                  <span class="glyphicon glyphicon-search"></span>
                <% end %>
              <% end %></li>
            <% end %>
            </li>
          </ul>
        </div> <!--end navbarcollapse-->
      </div> <!--end container fluid-->
    </nav> <!-- end navbar -->
    <div class= "page-content">
      <% if notice %>
        <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div class="page-wrap">
    </div>
    <footer>
      <div id="copyright"> &copy; 2018 MountainStyle</div>
    </footer>
  </body>
</html>